variables:
      VERSION: 7.2
pool:
  vmImage: "ubuntu-18.04"

steps:

  - script: echo $(dev)

  - script: npm install
  
  - script: npm install @playwright/test
  - script: npx playwright install 

    displayName: "Install browser dependencies"
  - script: npm i playwright-chromium

    displayName: "run test"

  #- script: npm run azure2
  - script: npm run cicdhydro

  - task: PublishPipelineArtifact@1
    displayName: "publish"
    condition: succeededOrFailed()
    inputs:
     targetPath: '$(System.DefaultWorkingDirectory)/index.html'
     artifact: 'test-results'
    continueOnError: true

