variables:
      VERSION: 7.2
pool:
  vmImage: "ubuntu-18.04"
  workingDir: '$(service_path)'

steps:

  - script: echo $(dev)

  - script: npm install
  
  - script: npm install @playwright/test
  - script: npx playwright install 

    displayName: "Install browser dependencies"
  - script: npm i playwright-chromium

    displayName: "run test"
  - script: npm run azurelogin
      
  - task: CopyFiles@2
    inputs:
    #leave it empty, the copying is done from the root folder
      #sourceFolder: '$(Build.SourcesDirectory)/_daniavander_hydro-test/playwright-report'
      Contents: 'playwright-report/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1    
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

