name: ci

variables:
      VERSION: 7.2
      timezone: Europe/Budapest
      
pool:
  #vmImage: "ubuntu-18.04"
  vmImage: 'ubuntu-20.04'
  workingDir: '$(service_path)'

schedules:
- cron: "0 10 * * Mon-Fri"
  displayName: M-F 3:00 AM (UTC) daily build
  branches:
    include:
    - main
    
jobs:
- job: AutomatedTests
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: npm install
  - script: npx playwright install --with-deps

    timeoutInMinutes: 7 # how long to run the job before automatically cancelling

    displayName: "run the test"
    condition: succeeded()
  - script: npm run smoke
  - script: npm run generate

  - task: AllureGenerate@1
  
    inputs:
      resultsDir: 'allure-results'
      targetDir: 'allure-report/$(Build.BuildNumber)'

  - task: CopyFiles@1
    condition: succeededOrFailed()            # Run task even if previous ones fail
    inputs:
    #leave it empty, the copying is done from the root folder
      #sourceFolder: '$(Build.SourcesDirectory)/_daniavander_hydro-test/playwright-report'
      contents: |
        playwright-report/**
        screenshot/**
        test-results/**
      targetFolder: '$(Build.ArtifactStagingDirectory)'