variables:
      VERSION: 7.2
pool:
  #vmImage: "ubuntu-18.04"
  vmImage: 'ubuntu-20.04'
  workingDir: '$(service_path)'

jobs:
- job: PreWork
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
    
  - script: npm install
  - script: npm ci
  - script: npm install @playwright/test
  - script: npx playwright install --with-deps
    displayName: "Install browser dependencies"
  - script: npm i playwright-chromium

    displayName: "run the test"
    condition: succeeded()
  - script: npm run smoke
      
      
  - task: CopyFiles@1
    condition: succeededOrFailed()            # Run task even if previous ones fail
    inputs:
    #leave it empty, the copying is done from the root folder
      #sourceFolder: '$(Build.SourcesDirectory)/_daniavander_hydro-test/playwright-report'
      contents: |
        playwright-report/**
        screenshot/**
        test-results/**
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      
      
  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'