name: ci

variables:
      VERSION: 7.2
      timezone: Europe/Budapest
      
pool:
  #vmImage: "ubuntu-18.04"
  vmImage: 'windows-latest'
  workingDir: '$(service_path)'

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: M-F 3:00 AM (UTC) daily build
  branches:
    include:
    - main
  always: true
    
jobs:
- job: AutomatedTests
  timeoutInMinutes: 30 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 33 # how much time to give 'run always even if cancelled tasks' before killing them
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  - script: which node

    displayName: "Install framework"
  - script: npm install
  #- script: npx playwright install --with-deps

    displayName: "Execute test"
    condition: succeededOrFailed()
  - script: npm run smoke
  #- script: npm run generate

 #  displayName: "Run test"
 #  condition: succeededOrFailed()
 #- script: npm run generate
  

  #- task: AllureGenerate@1
  #  inputs:
  #    resultsDir: 'allure-results'
  #    targetDir: 'allure-report/$(Build.BuildNumber)'

  - task: PublishHtmlReport@1
    condition: succeededOrFailed()
    inputs:
      reportDir: 'playwright-report/index.html'


  - task: CopyFiles@1
    condition: succeededOrFailed()            # Run task even if previous ones fail
    inputs:
    #leave it empty, the copying is done from the root folder
      #sourceFolder: '$(Build.SourcesDirectory)/_daniavander_hydro-test/playwright-report'
      contents: |
        playwright-report/**
        screenshot/**
        test-results/**
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    condition: succeededOrFailed()
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'