variables:
      VERSION: 7.2
pool:
  vmImage: "ubuntu-18.04"

steps:
  #- task: Bash@3

  - script: echo $(dev)

  - script: npm install
  
  - script: npm install @playwright/test

    displayName: "Install browser dependencies"
  - script: npm i playwright-chromium

    displayName: "run test"
  #- script: npm run cicdtesthydro
  - script: npm run cicd

steps:
  - task: PublishPipelineArtifact@1
    displayName: "publish"
    inputs:
     targetPath: '**/*.html'
     artifact: 'test-results'
    continueOnError: true
